var colors = ["Red", "Green", "Blue", "Orange", "Purple", "Grey"];
document.write("<b> Initial array: </b>" + colors + "<br>");
var userC1 = prompt("What color would you like to add at the beginning of the array?");
colors.unshift(userC1);
document.write("<b> A. </b>" + colors + "<br>");
var userC2 = prompt("What color would you like to add at the end of the array?");
colors.push(userC2);
document.write("<b> B. </b>" + colors + "<br>");
colors.unshift("Maroon", "Cyan");
document.write("<b> C. </b>" + colors + "<br>");
colors.shift();
document.write("<b> D. </b>" + colors + "<br>");
colors.pop();
document.write("<b> E. </b>" + colors + "<br>");
var indx = prompt("At which index of the array, would you like to add a color?");
indx = parseInt(indx);
var userC3 = prompt("And what color would you like to add to the selected index?");
colors.splice(indx, 0, userC3);
document.write("<b> F. </b>" + colors + "<br>");
var indx2 = prompt("At which index of the array would you like to delete color(s)?");
var dltNumb = prompt("And how many colors would you like to delete from the selected index?");
colors.splice(indx2, dltNumb);
document.write("<b> G. </b>" + colors + "<br>");