var x = 25;
document.write('<span style="color:grey; font-size: 25px">' + "Result:");
document.write("<br>");
document.write("The value of x is: " + x);
document.write("<br>");
document.write("...........................................");
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write("The value of ++x is: " + ++x);
document.write("<br>");
document.write("Now the value of x is: " + x);
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write("The value of x++ is: " + x++);
document.write("<br>");
document.write("Now the value of x is: " + x);
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write("The value of --x is: " + --x);
document.write("<br>");
document.write("Now the value of x is: " + x);
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write("The value of x-- is: " + x--);
document.write("<br>");
document.write("Now the value of x is: " + x);